name: JobGenie Cron Trigger

on:
  schedule:
    - cron: "0 0 * * *"   # runs once every day at 00:00 UTC
  workflow_dispatch: {}   # lets you trigger manually too

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API endpoint
        run: |
          curl -sS -X GET "https://the-job-genie.vercel.app/api/send-daily-mails" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
